### ISSUE TITLE
Re-installed wordpress 12/04/19

### ISSUE THREAD

**Issue by rpmoses** [rpmoses/capstoneTeam6#3]
Issue with the re installation was it could not find php file. Needed to ask Dr. Schofield to help trouble shot this. We used the direction form the website https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-lamp-on-ubuntu-16-04. Seemed to not work properly.

**Comment by Mforbus1** [comment]
Worked on this for a few hours, was not making any progress. After discussion with Prof. Schofield and a few more minutes of bug testing, we found the issue to be a PHP module not loaded within Apache. The Wordpress installation functioned after that and we were able to begin work on the website after this.
