### ISSUE TITLE
Apache2 is not connected to wordpress correctly

### ISSUE THREAD

**Issue by rpmoses** [rpmoses/capstoneTeam6#4]
After appropriately installing Wordpress, viewing a build of the website comes up with a blank page.

**Comment by rpmoses** [comment]
Working with professor Schofield to fix  this.

**Comment by Mforbus1** [comment]
When trying to connect to the homepage of the website, the site is not accessing anything on the website

**Comment by Mforbus1** [comment]
Something got changed. Maybe it was the wp-config.php 'wp_debug_display' or looking at the performance analytics in mozilla firefox, but the site somehow functions now. Nice work team.
