### ISSUE TITLE
WP database sync across multiple developers 

### ISSUE THREAD

**Issue by rpmoses** [rpmoses/capstoneTeam6#5]
12/05/2019 We had an issue where we didn't have our wp database sync with our wordpress updates. This means that any changes we make to the wordpress in the VM would not be saved for version control. Professor Schoolchild sent us an article to configure this. Here is the link: https://wordpress.stackexchange.com/questions/52725/keeping-wp-database-synced-across-multiple-developers-using-git

**Comment by Mforbus1** [comment]
Used the Import/Export functionality to export the website data to an XML file and added that file into the GitHub repository.
